[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
# Whenever an advisory is detected by the rules above, it should either be dealt with, or added
# to the following list of advisories that we can't deal with.
# The entries below should be removed over time but are considered to not be actual problems.
ignore = [
    "RUSTSEC-2020-0057",  # TODO: deprecated crate "block-cipher"
    "RUSTSEC-2020-0058",  # TODO: deprecated crate "stream-cipher"
]

[licenses]
unlicensed = "deny"
copyleft = "allow"
allow-osi-fsf-free = "either"
default = "deny"

[bans]
multiple-versions = "warn"
wildcards = "warn"  # TODO: should be "deny", but this fails when we have git dependencies

# TODO: deny git dependencies with a `[sources]` section

# The `openssl` and `ring` libraries are easy to accidentally pull in, and are too annoying to
# compile on a wide range of platforms.
[[bans.deny]]
name = "openssl"
[[bans.deny]]
name = "ring"
