[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
unlicensed = "deny"
copyleft = "allow"
allow-osi-fsf-free = "either"
default = "deny"

[bans]
multiple-versions = "warn"
wildcards = "warn"  # TODO: should be "deny", but this fails when we have git dependencies

# TODO: deny git dependencies with a `[sources]` section

# The `openssl` and `ring` libraries are easy to accidentally pull in, and are too annoying to
# compile on a wide range of platforms.
[[bans.deny]]
name = "openssl"
[[bans.deny]]
name = "ring"
