version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    labels: []
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: "/"
    labels: []
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
