pull_request_rules:
  - name: automatic merge when CI passes on main
    conditions:
      - check-success=all-ci
      - check-success=all-deploy
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        strict: true
        method: squash
