queue_rules:
  - name: default
    conditions:
      - check-success=all-ci
      - check-success=all-deploy
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      
pull_request_rules:
  - name: automatic merge when CI passes on main
    conditions:
      - check-success=all-ci
      - check-success=all-deploy
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
    actions:
      queue:
        name: default
        method: squash
