[package]
name = "substrate-lite"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Primitives to build a client for Substrate-based blockchains"
repository = "https://github.com/paritytech/substrate-lite"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
edition = "2018"
readme = "README.md"
keywords = ["blockchain", "peer-to-peer"]
default-run = "full-node"

[workspace]
members = [
    "bin/browser-node",
]

[features]
default = ["std"]
std = [
    "app_dirs",
    "async-std",
    "async-tls",
    "atty",
    "corooteen",
    "futures/std",
    "futures/thread-pool",
    "futures-timer",
    "rand/std",
    "rand_chacha/std",
    "soketto",
    "structopt",
    "terminal_size",
    "url",
    "wasmtime",
    "webpki",
]
wasm-bindings = [
    "futures-timer/wasm-bindgen",
    "js-sys",
    "rand/wasm-bindgen",
    "send_wrapper",
    "std",
    "wasm-bindgen",
    "web-sys",
]

[[bin]]
name = "full-node"
path = "bin/full-node/main.rs"
required-features = ["std"]

[[bin]]
name = "json-rpc-test"
path = "bin/json-rpc-test/main.rs"
required-features = ["std"]

[dependencies]
# This section contains only no_std-compatible crates. See below for std-only crates.
#
# Before adding a crate here, please make sure that it is `no_std`-compatible. If a crate should
# theoretically be `no_std`-compatible (i.e. doesn't need the help of the operating system) but is
# not, or if things are sketchy, please leave a comment next to it.
ahash = { version = "0.5.6", default-features = false }
arrayvec = { version = "0.5.2", default-features = false }
atomic = "0.5.0"
blake2-rfc = { version = "0.2.18", default-features = false }
bs58 = { version = "0.3.1", default-features = false, features = ["alloc"] }
derive_more = "0.99.7"
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["alloc", "batch", "u64_backend"] }
either = { version = "1.6.1", default-features = false }
fnv = { version = "1.0.7", default-features = false }
hashbrown = { version = "0.9.1", default-features = false, features = ["serde"] }   # TODO: remove serde feature
hex = { version = "0.4.2", default-features = false }
libsecp256k1 = { version = "0.3.5", default-features = false }
lru = "0.6.0"   # TODO: audit the unsafe code in that crate
merlin = { version = "2.0", default-features = false }
multihash = "0.11.4"  # TODO: waiting for a crates.io publication of https://github.com/multiformats/rust-multihash/pull/82 that adds no_std support
nom = "5.1.2"  # TODO: nom has a disableable `std` feature, but disabling it requires nightly; waiting for version 6.0
num-bigint = { version = "0.3.0", default-features = false }
num-rational = "0.3.0"  # TODO: there's a fuck-up in their source code that prevents disabling `std`
num-traits = { version = "0.2.12", default-features = false }
parity-multiaddr = "0.9.2" # TODO: doesn't support no_std
pin-project = "1.0.1"
prost = "0.6.1"  # TODO: waiting for a published version that supports no_std
rand = { version = "0.7.3", default-features = false }
rand_chacha = { version = "0.2.2", default-features = false }
schnorrkel = { git = "https://github.com/w3f/schnorrkel", rev = "cfdbe9ae865a4d3ffa2566d896d4dbedf5107028", features = ["preaudit_deprecated"] } # TODO: waiting for a publication { version = "0.9.1", default-features = false, features = ["preaudit_deprecated"] }
serde = { version = "1.0.117", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.59", default-features = false, features = ["alloc", "raw_value"] }
sha2 = { version = "0.9.1", default-features = false }
slab = "0.4.2"  # TODO: doesn't support no_std and is unmaintained :-/
smallvec = "1.4.2"
snow = { version = "0.7.2", default-features = false, features = ["default-resolver"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }
twox-hash = "1.6.0"
wasmi = { version = "0.7.0", default-features = false, features = ["core"] }  # TODO: having to add `core` is sketchy; maybe report this

# `std` feature
# Add here the crates that cannot function without the help of the operating system or environment.
app_dirs = { version = "1.2.1", optional = true }
async-std = { version = "1.6.5", optional = true }
async-tls = { version = "0.10.0", optional = true }
atty = { version = "0.2.14", optional = true }
futures = { version = "0.3.6", default-features = false, optional = true }
futures-timer = { version = "3.0", optional = true }
soketto = { version = "0.4.2", optional = true }
structopt = { version = "0.3.20", optional = true, default-features = false, features = ["color", "suggestions", "wrap_help"] }
terminal_size = { version = "0.1.12", optional = true }
url = { version = "2.1.1", optional = true }
webpki = { version = "0.21.0", optional = true }

# `wasm-bindings` feature
js-sys = { version = "0.3.45", optional = true }
send_wrapper = { version = "0.5.0", optional = true }
wasm-bindgen = { version = "0.2.68", optional = true }
web-sys = { version = "0.3.44", optional = true, features = ["BinaryType", "CloseEvent", "DomException", "Event", "Storage", "WebSocket", "Window"] }

# BELOW: DEPENDENCIES TO REMOVE
# TODO:
anyhow = "1.0.31"  # TODO: wasmtime returns these errors for some reason
impl-serde = "0.2.3"  # TODO: that looks like a hack
parity-scale-codec = { version = "1.0.0", features = ["derive"] } # TODO: a lot of unnecessary overhead in terms of memory allocations

[target.'cfg(target_arch = "x86_64")'.dependencies]
# `std` feature
corooteen = { git = "https://github.com/tomaka/corooteen", optional = true } # TODO: CRITICAL /!\ this code is veeery unsafe at the moment
wasmtime = { version = "0.20.0", default-features = false, optional = true }

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
async-std = "1.6.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.dev]
opt-level = 2
panic = "abort"
[profile.dev.package."*"]
opt-level = 3

# The `test` profile mimics the `dev` profile to avoid recompilations.
[profile.test]
opt-level = 2
[profile.test.package."*"]
opt-level = 3

[profile.release]
panic = "abort"
lto = true
#strip = "symbols"      # TODO: uncomment once stable
