[package]
name = "substrate-lite"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
edition = "2018"
keywords = ["blockchain", "peer-to-peer"]
default-run = "full-node"

[workspace]
members = [
    "bin/browser-node",
]

[features]
default = ["os-networking"]
os-networking = [
    "async-std",
    "async-tls",
    "soketto",
    "url",
    "webpki",
]
wasm-bindings = [
    "chrono/wasmbind",
    "futures-timer/wasm-bindgen",
    "js-sys",
    "rand/wasm-bindgen",
    "wasm-bindgen",
    "web-sys",
]

[[bin]]
name = "full-node"
path = "bin/full-node/main.rs"
required-features = ["os-networking"]

[[bin]]
name = "json-rpc-test"
path = "bin/json-rpc-test/main.rs"
required-features = ["os-networking"]

[dependencies]
ahash = { version = "0.4.5", default-features = false }
app_dirs = "1.2.1"
arrayvec = "0.5.1"
atomic = "0.5.0"
blake2-rfc = { version = "0.2.18", default-features = false }
bs58 = { version = "0.3.1", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", features = ["serde"] }   # TODO: remove serde feature
derive_more = "0.99.7"
ed25519-dalek = { version = "1.0.0", default-features = false, features = ["alloc", "batch", "u64_backend"] }
either = "1.6.1"
env_logger = "0.8.1"
fnv = "1.0"
futures = { version = "0.3.6", features = ["thread-pool"] }   # TODO: should be default-features = false, but we use some std-only types at the moment
futures-timer = "3.0"
hashbrown = { version = "0.9.1", default-features = false, features = ["serde"] }   # TODO: remove serde feature
hex = { version = "0.4.2", default-features = false }
isatty = "0.1.9"
libsecp256k1 = "0.3.5"
lru = "0.6.0"   # TODO: audit the unsafe code in that crate
merlin = { version = "2.0", default-features = false }
multihash = "0.11.4"
nom = "5.1.2"
num-bigint = "0.3.0"
num-rational = "0.3.0"
num-traits = "0.2.12"
parity-multiaddr = "0.9.2"
parking_lot = "0.11.0"
pin-project = "0.4.26"
prost = "0.6.1"
rand = "0.7.0"
rand_chacha = "0.2.2"
schnorrkel = { git = "https://github.com/w3f/schnorrkel", rev = "cfdbe9ae865a4d3ffa2566d896d4dbedf5107028", features = ["preaudit_deprecated"] } # TODO: waiting for a publication { version = "0.9.1", default-features = false, features = ["preaudit_deprecated"] }
send_wrapper = "0.5.0"
serde = { version = "1.0.117", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.59", default-features = false, features = ["alloc", "raw_value"] }
sha2 = "0.9.1"
slab = "0.4.2"
smallvec = "0.6.10"
snow = { version = "0.7.2", default-features = false, features = ["default-resolver"] }
structopt = { version = "0.3.17", default-features = false, features = ["color", "suggestions", "wrap_help"] }
terminal_size = "0.1.12"
tiny-keccak = { version = "2.0", features = ["keccak"] }
twox-hash = "1.5.0"
unsigned-varint = { version = "0.3.1", features = ["futures", "futures-codec"] }
wasmi = "0.6.2"

# `os-networking` feature
async-std = { version = "1.6.2", optional = true }
async-tls = { version = "0.7.0", optional = true }
soketto = { version = "0.4.0", optional = true }
url = { version = "2.1.1", optional = true }
webpki = { version = "0.21.0", optional = true }

# `wasm-bindings` feature
js-sys = { version = "0.3.44", optional = true }
wasm-bindgen = { version = "0.2.68", optional = true }
web-sys = { version = "0.3.44", optional = true, features = ["BinaryType", "CloseEvent", "DomException", "Event", "Storage", "WebSocket", "Window"] }

# BELOW: DEPENDENCIES TO REMOVE
# TODO:
anyhow = "1.0.31"  # TODO: wasmtime returns these errors for some reason
impl-serde = "0.2.3"  # TODO: that looks like a hack
parity-scale-codec = { version = "1.0.0", features = ["derive"] } # TODO: a lot of unnecessary overhead in terms of memory allocations
primitive-types = { version = "0.6.2", default-features = false, features = ["codec", "serde", "std"] } # TODO: nothing wrong with this one, but ideally don't use parity crates

[target.'cfg(target_arch = "x86_64")'.dependencies]
corooteen = { git = "https://github.com/tomaka/corooteen" } # TODO: CRITICAL /!\ this code is veeery unsafe at the moment
wasmtime = { version = "0.18.0", default-features = false }

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
async-std = "1.6.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.dev]
opt-level = 2
panic = "abort"
[profile.dev.package."*"]
opt-level = 3

# The `test` profile mimics the `dev` profile to avoid recompilations.
[profile.test]
opt-level = 2
[profile.test.package."*"]
opt-level = 3

[profile.release]
panic = "abort"
lto = true
#strip = "symbols"      # TODO: uncomment once stable
