name: recurrent-audit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow triggering through the UI

permissions:
  contents: read
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
