# Smoldot
# Copyright (C) 2019-2021  Parity Technologies (UK) Ltd.
# SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: cache-fill

# Pull requests are only able to load the build cache of the branch they're based upon. In order
# for this to work, we must therefore build this cache for the `main` branch. This GitHub actions
# workflow is dedicated to this task.
#
# See also <https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache>

on:
  push:
    branches:
      - main

jobs:
  test-64bits:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: Swatinem/rust-cache@v1
    - run: RUSTFLAGS=-Dwarnings cargo test --no-run --locked --workspace --all-features

  test-32bits:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v2.4.0
    - run: apt-get update && apt-get install -y libc6-dev-i386
    - uses: Swatinem/rust-cache@v1
    - run: rustup target add i686-unknown-linux-gnu
    - run: RUSTFLAGS=-Dwarnings cargo test --no-run --target i686-unknown-linux-gnu --locked --workspace --all-features

  wasm-node-check:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: Swatinem/rust-cache@v1
    - uses: actions/setup-node@v2.5.0
      with:
        node-version: '12'
    - run: RUSTFLAGS=-Dwarnings cd bin/wasm-node/javascript && npm ci && npm run-script build

  wasm-node-size-diff:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: Swatinem/rust-cache@v1
    - uses: actions/setup-node@v2.5.0
      with:
        node-version: '12'
    - run: cd bin/wasm-node/javascript && npm ci && npm run-script build

  check-features:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: Swatinem/rust-cache@v1
    - run: RUSTFLAGS=-Dwarnings cargo check --workspace

  clippy:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: Swatinem/rust-cache@v1
    - run: cargo check --workspace
